#!/bin/bash

argparse() {
    while :; do
        case "${1-}" in
            -f|--input-dl2)
                input_dl2=$(readlink -f "${2-}")
                run_id="${2-}"
                run_id="${run_id##*Run}"
                run_id="${run_id%.*}"
                shift
                ;;
            -o|--output-dl3-path)
                output_dl3=$(readlink -f "${2-}")
                shift
                ;;
            -p|--input-irf)
                input_irf=$(readlink -f "${2-}")
                shift
                ;;
            -c|--global-gh-cut)
                global_gh_cut="${2-}"
                shift
                ;;
            --source-name)
                source="${2-}"
                shift
                ;;
            *) break ;;
        esac
        shift
    done

    return 0
}

argparse "$@"

cmd="lstchain_create_dl3_file "
cmd+=" --input-dl2 ${input_dl2} "
cmd+=" --output-dl3-path ${output_dl3} "
cmd+=" --input-irf ${input_irf} "
cmd+=" --global-gh-cut ${global_gh_cut} "
cmd+=" --source-name ${source} "

 sbatch \
    --mem=12G \
    -o $(readlink -f build/dl3_${run_id}.stdout) \
    -e $(readlink -f build/dl3_${run_id}.stderr) \
    --wrap="$cmd"
