general:
  log:
    level: info

observations:
  datastore: build/dl3
  obs_time:
    start: null
    stop: null
  required_irf:
    - aeff
    - edisp

datasets:
  type: 1d
  stack: true
  geom:
    wcs:
      skydir: { frame: galactic, lon: 179.88 deg, lat: 65.01 deg }
      binsize: 0.02 deg
      width: { width: 2.0 deg, height: 2.0 deg }
      binsize_irf: 0.2 deg
    selection: { offset_max: 2.5 deg }
    axes:
      energy:
        min: 20 GeV
        max: 10 TeV
        nbins: 40
      energy_true:
        min: 20 GeV
        max: 10 TeV
        nbins: 20
  background:
    method: "reflected"
    parameters: { min_distance_input: 10 deg }
  on_region:
    { frame: galactic, lon: 283.74 deg, lat: 74.49 deg, radius: 0.2 deg }
  containment_correction: false

fit:
  fit_range: { min: 20 GeV, max: 10 TeV }

flux_points:
  energy: { min: 20 GeV, max: 10 TeV, nbins: 20 }
  source: M87

light_curve:
  energy_edges: { min: 100 GeV, max: 10 TeV, nbins: 1 }
  source: M87
